In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('weather_dataset_2025.csv')

In [3]:
df.head()

,Date,City,Temperature_C,Humidity_%,Wind_Speed_km_h,Precipitation_mm,Condition
0,2025-01-01,Riyadh,15.8,94,21.0,0.00,Cloudy
1,2025-01-01,Jeddah,31.5,54,25.3,3.71,Windy
2,2025-01-01,Dammam,30.4,33,8.6,3.14,Partly Cloudy
3,2025-01-01,Dubai,34.0,37,18.7,0.00,Foggy
4,2025-01-01,Doha,28.3,32,6.8,0.00,Rainy

**Opening a CSV File from an URL**

In [4]:
import requests
from io import StringIO

url='https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv'
headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url,headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

**Sep Parameter**

In [5]:
titanic=pd.read_csv("titanic.tsv",sep='\t',names=["PassengerId","Survived","Pclass","Name","Sex","Age","SibSp","Parch","Ticket","Fare","Cabin","Embarked"])

In [6]:
titanic.to_csv("Titanic.csv",index=False)

**Index_col parameter**

In [7]:
pd.read_csv('weather_dataset_2025.csv',index_col='Date')

,City,Temperature_C,Humidity_%,Wind_Speed_km_h,Precipitation_mm,Condition
Date,,,,,,
2025-01-01,Riyadh,15.8,94,21.0,0.00,Cloudy
2025-01-01,Jeddah,31.5,54,25.3,3.71,Windy
2025-01-01,Dammam,30.4,33,8.6,3.14,Partly Cloudy
2025-01-01,Dubai,34.0,37,18.7,0.00,Foggy
2025-01-01,Doha,28.3,32,6.8,0.00,Rainy
...,...,...,...,...,...,...
2025-12-31,Sydney,33.5,71,22.9,4.88,Sunny
2025-12-31,Toronto,9.1,43,37.4,5.03,Sunny
2025-12-31,Berlin,6.3,42,23.7,10.68,Windy
2025-12-31,Mumbai,27.6,58,12.5,3.23,Cloudy
2025-12-31,Singapore,44.3,75,4.6,0.00,Stormy

**Header parameter**

In [8]:
pd.read_csv('Train_Status.csv',header=1)

   0  0.1  0.2  0.3  1234  50     Rampur
0  1    1    1    1  5678  56  Sultanpur
1  2    2    2    2  5342  89    Vidisha
2  3    3    3    3  6678  70     Bhopal

**use_cols parameter**

In [9]:
pd.read_csv('weather_dataset_2025.csv',usecols=['Date','City','Temperature_C','Condition'])

            Date       City  Temperature_C      Condition
0     2025-01-01     Riyadh           15.8         Cloudy
1     2025-01-01     Jeddah           31.5          Windy
2     2025-01-01     Dammam           30.4  Partly Cloudy
3     2025-01-01      Dubai           34.0          Foggy
4     2025-01-01       Doha           28.3          Rainy
...          ...        ...            ...            ...
5470  2025-12-31     Sydney           33.5          Sunny
5471  2025-12-31    Toronto            9.1          Sunny
5472  2025-12-31     Berlin            6.3          Windy
5473  2025-12-31     Mumbai           27.6         Cloudy
5474  2025-12-31  Singapore           44.3         Stormy

[5475 rows x 4 columns]

**Squeeze parameters**

In [10]:
pd.read_csv('weather_dataset_2025.csv',usecols=['City'])['City']

0          Riyadh
1          Jeddah
2          Dammam
3           Dubai
4            Doha
          ...
5470       Sydney
5471      Toronto
5472       Berlin
5473       Mumbai
5474    Singapore
Name: City, Length: 5475, dtype: object

**Skiprows/nrows Parameter**

In [11]:
pd.read_csv("weather_dataset_2025.csv",skiprows=[0,10])

      2025-01-01     Riyadh  15.8  94  21.0    0.0         Cloudy
0     2025-01-01     Jeddah  31.5  54  25.3   3.71          Windy
1     2025-01-01     Dammam  30.4  33   8.6   3.14  Partly Cloudy
2     2025-01-01      Dubai  34.0  37  18.7   0.00          Foggy
3     2025-01-01       Doha  28.3  32   6.8   0.00          Rainy
4     2025-01-01      Cairo  12.8  60  17.8   9.14          Sunny
...          ...        ...   ...  ..   ...    ...            ...
5468  2025-12-31     Sydney  33.5  71  22.9   4.88          Sunny
5469  2025-12-31    Toronto   9.1  43  37.4   5.03          Sunny
5470  2025-12-31     Berlin   6.3  42  23.7  10.68          Windy
5471  2025-12-31     Mumbai  27.6  58  12.5   3.23         Cloudy
5472  2025-12-31  Singapore  44.3  75   4.6   0.00         Stormy

[5473 rows x 7 columns]

In [12]:
pd.read_csv('weather_dataset_2025.csv',nrows=100)

,Date,City,Temperature_C,Humidity_%,Wind_Speed_km_h,Precipitation_mm,Condition
0,2025-01-01,Riyadh,15.8,94,21.0,0.00,Cloudy
1,2025-01-01,Jeddah,31.5,54,25.3,3.71,Windy
2,2025-01-01,Dammam,30.4,33,8.6,3.14,Partly Cloudy
3,2025-01-01,Dubai,34.0,37,18.7,0.00,Foggy
4,2025-01-01,Doha,28.3,32,6.8,0.00,Rainy
...,...,...,...,...,...,...,...
95,2025-01-07,Cairo,32.1,34,35.5,0.00,Foggy
96,2025-01-07,London,9.8,94,27.9,5.43,Windy
97,2025-01-07,New York,40.3,48,11.7,5.18,Partly Cloudy
98,2025-01-07,Tokyo,40.1,74,30.8,8.42,Sunny
99,2025-01-07,Paris,42.7,38,16.1,10.38,Partly Cloudy

**Skip bad lines**

In [13]:
pd.read_csv('netflix_movies (1).csv',sep=';',encoding='latin-1',on_bad_lines='skip')

     show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0     s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,...
1     s2,TV Show,Blood & Water,,"Ama Qamata, Khosi N...
2     s3,TV Show,Ganglands,Julien Leclercq,"Sami Bou...
3     s4,TV Show,Jailbirds New Orleans,,,,"September...
4     s5,TV Show,Kota Factory,,"Mayur More, Jitendra...
...                                                 ...
8798  s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo...
8799  s8804,TV Show,Zombie Dumb,,,,"July 1, 2019",20...
8800  s8805,Movie,Zombieland,Ruben Fleischer,"Jesse ...
8801  s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Cour...
8802  s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal,...

[8803 rows x 1 columns]

**dtypes parameter**

In [14]:
pd.read_csv('netflix_movies (1).csv',dtype={'release_year':int})

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

**Handling Dates**

In [15]:
pd.read_csv('netflix_movies (1).csv',parse_dates=['release_year']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   datetime64[ns]
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), object(11)
memory usage: 825.8+ KB

In [16]:
def rename(name):
    if name =="Kota Factory":
        return "KF"
    else:
        return name

In [34]:
rename("Kota Factory")

'KF'

**Convertors**

In [35]:
pd.read_csv('netflix_movies (1).csv',converters={'title':rename})

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,KF,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

**na_values parameters**

In [36]:
pd.read_csv('weather_dataset_2025.csv',na_values=['Mumbai'])

,Date,City,Temperature_C,Humidity_%,Wind_Speed_km_h,Precipitation_mm,Condition
0,2025-01-01,Riyadh,15.8,94,21.0,0.00,Cloudy
1,2025-01-01,Jeddah,31.5,54,25.3,3.71,Windy
2,2025-01-01,Dammam,30.4,33,8.6,3.14,Partly Cloudy
3,2025-01-01,Dubai,34.0,37,18.7,0.00,Foggy
4,2025-01-01,Doha,28.3,32,6.8,0.00,Rainy
...,...,...,...,...,...,...,...
5470,2025-12-31,Sydney,33.5,71,22.9,4.88,Sunny
5471,2025-12-31,Toronto,9.1,43,37.4,5.03,Sunny
5472,2025-12-31,Berlin,6.3,42,23.7,10.68,Windy
5473,2025-12-31,NaN,27.6,58,12.5,3.23,Cloudy
5474,2025-12-31,Singapore,44.3,75,4.6,0.00,Stormy

**Loading a huge datasets in chucks**

In [37]:
dfs=pd.read_csv("weather_dataset_2025.csv",chunksize=5000)

In [39]:
for chunks in dfs:
    print(chunks.shape)

(475, 7)